### ISSUE TITLE
おつかいをする

### ISSUE THREAD

**Issue by SEKI-YUTA** [illionillion/oss-blog#82]
### 詳細な説明

あんぱん
サラダチキン
栄養ゼリー

### 追加情報

- [ ] UI/UXの変更が必要
- [ ] ドキュメントの更新が必要
- [ ] テストが必要

**Comment by SEKI-YUTA** [comment]
![Uploading PXL_20240915_054203219.jpg…]()

**Comment by SEKI-YUTA** [comment]
![PXL_20240915_054203219](https://github.com/user-attachments/assets/eb3183d9-2290-45a7-b5a3-2b6dfca390df)

**Comment by SEKI-YUTA** [comment]
お使いが完了したのでClose

**Comment by hatimaruuuu** [comment]
宅配完了
